version: "3.8"

name: datasets

services:
  datasets:
    build:
      context: ../../
      dockerfile: build/Dockerfile
    depends_on:
      - db-migrator
    tmpfs:
      - /dev/shm:rw,noexec,nosuid,size=1g
    environment:
      - DOTENV_FILE=configs/dev/.env
      - DB_CONNECT_STRING=postgresql://hseuser:P@ssw0rd@db:5432/hsedb
      - DATASETS_DB_CONNECT_STRING=postgresql://hseuser:P@ssw0rd@datasetsdb:5432/datasetsdb
      - MINIO_ADDR=minio:9000
      - LAUNCHER_ADDR=launcher:8087
      - HOST=tcarzverey.ru:9000
    ports:
      - "8083:8083"
      - "8084:8084"
    networks:
      - auth_hse-net

  db-migrator:
    build:
      context: ../../
      dockerfile: build/migrate/Dockerfile
    command: ["postgresql://hseuser:P@ssw0rd@datasetsdb:5432/datasetsdb", "up"]
    depends_on:
      - datasetsdb
    networks:
      - auth_hse-net

  datasetsdb:
   image: postgres:16
   restart: always
   environment:
     - POSTGRES_DB=datasetsdb
     - POSTGRES_USER=hseuser
     - POSTGRES_PASSWORD=P@ssw0rd
     - PGDATA=/var/lib/postgresql/data/pgdata
   ports:
     - '6433:5432'
   volumes:
     - db-data:/var/lib/postgresql/data
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready -U hseuser -d datasetsdb" ]
     interval: 10s
     timeout: 5s
     retries: 5
     start_period: 10s
   networks:
     - auth_hse-net

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: hse_minio_user
      MINIO_ROOT_PASSWORD: hse_minio_password
    volumes:
      - ~/minio/data:/data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
    networks:
      - auth_hse-net

volumes:
  db-data:
    driver: local

networks:
  auth_hse-net:
    external: true